CREATE TABLE trip_stations
(

    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,

    trip_id    BIGINT      NOT NULL,
    station_id BIGINT      NOT NULL,

    stop_order INTEGER     NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_trip_stations
        PRIMARY KEY (id),

    CONSTRAINT fk_trip_stations_trip
        FOREIGN KEY (trip_id)
            REFERENCES trips (id),

    CONSTRAINT fk_trip_stations_station
        FOREIGN KEY (station_id)
            REFERENCES stations (id),

    CONSTRAINT uq_trip_stations_trip_station
        UNIQUE (trip_id, station_id),

    CONSTRAINT uq_trip_stations_trip_order
        UNIQUE (trip_id, stop_order),

    CONSTRAINT chk_trip_stations_stop_order_positive
        CHECK (stop_order > 0)
);