CREATE TABLE service_zones
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(100) NOT NULL,

    area extensions.geometry(Polygon, 4326) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_service_zones
        PRIMARY KEY (id),

    CONSTRAINT chk_service_zones_name_not_blank
        CHECK (BTRIM(name) <> '')
);

CREATE INDEX idx_service_zones_area
    ON service_zones
    USING GIST (area);