CREATE TABLE trip_station_presence (
    trip_station_presence_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id BIGINT NOT NULL,
    station_id BIGINT NOT NULL,
    consecutive_inside_count INTEGER NOT NULL DEFAULT 0,
    arrival_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    last_observed_at TIMESTAMPTZ,

    CONSTRAINT fk_trip_station_presence_trip
        FOREIGN KEY (trip_id) REFERENCES trips (id) ON DELETE CASCADE,
    CONSTRAINT fk_trip_station_presence_station
        FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE CASCADE,
    CONSTRAINT uk_trip_station_presence_trip_station
        UNIQUE (trip_id, station_id),
    CONSTRAINT chk_trip_station_presence_count
        CHECK (consecutive_inside_count >= 0)
);

CREATE INDEX idx_trip_station_presence_trip_id
    ON trip_station_presence (trip_id);
