CREATE TABLE route_stations
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    route_id              BIGINT      NOT NULL,
    station_id            BIGINT      NOT NULL,
    stop_order            INTEGER     NOT NULL,
    expected_arrival_time TIME        NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_route_stations PRIMARY KEY (id),
    CONSTRAINT fk_route_stations_route
        FOREIGN KEY (route_id) REFERENCES routes (id),
    CONSTRAINT fk_route_stations_station
        FOREIGN KEY (station_id) REFERENCES stations (id),
    CONSTRAINT uq_route_stations_route_station
        UNIQUE (route_id, station_id),
    CONSTRAINT uq_route_stations_route_order
        UNIQUE (route_id, stop_order),
    CONSTRAINT chk_route_stations_stop_order_positive
        CHECK (stop_order > 0)
);

ALTER TABLE trip_stations
    ADD COLUMN expected_arrival_time TIME;

UPDATE trip_stations trip_station
SET expected_arrival_time = trip.scheduled_start_time::TIME
FROM trips trip
WHERE trip.id = trip_station.trip_id;

ALTER TABLE trip_stations
    ALTER COLUMN expected_arrival_time SET NOT NULL,
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD CONSTRAINT chk_trip_stations_status
        CHECK (status IN ('ACTIVE', 'SKIPPED'));
