CREATE TABLE buses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,

    bus_number VARCHAR(50) NOT NULL,
    capacity   INTEGER     NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_buses
        PRIMARY KEY (id),

    CONSTRAINT uq_buses_bus_number
        UNIQUE (bus_number),

    CONSTRAINT chk_buses_bus_number_not_blank
        CHECK (BTRIM(bus_number) <> ''),

    CONSTRAINT chk_buses_capacity_positive
        CHECK (capacity > 0),

    CONSTRAINT chk_buses_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);