CREATE TABLE routes
(

    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name       VARCHAR(100) NOT NULL,

    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_routes
        PRIMARY KEY (id),

    CONSTRAINT uq_routes_name
        UNIQUE (name),

    CONSTRAINT chk_routes_name_not_blank
        CHECK (BTRIM(name) <> ''),

    CONSTRAINT chk_routes_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

