CREATE TABLE stations
(

    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name       VARCHAR(100)  NOT NULL,

    address    VARCHAR(255),

    latitude   NUMERIC(9, 6) NOT NULL,
    longitude  NUMERIC(9, 6) NOT NULL,

    status     VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_stations
        PRIMARY KEY (id),

    CONSTRAINT chk_stations_name_not_blank
        CHECK (BTRIM(name) <> ''),

    CONSTRAINT chk_stations_latitude
        CHECK (latitude BETWEEN -90 AND 90),

    CONSTRAINT chk_stations_longitude
        CHECK (longitude BETWEEN -180 AND 180),

    CONSTRAINT chk_stations_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);