CREATE TABLE trips
(

    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,

    route_id             BIGINT      NOT NULL,
    bus_id               BIGINT      NOT NULL,
    driver_id            BIGINT      NOT NULL,

    scheduled_start_time TIMESTAMPTZ NOT NULL,
    actual_start_time    TIMESTAMPTZ,
    actual_end_time      TIMESTAMPTZ,

    current_latitude     NUMERIC(9, 6),
    current_longitude    NUMERIC(9, 6),
    location_updated_at  TIMESTAMPTZ,

    status               VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',

    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_trips
        PRIMARY KEY (id),

    CONSTRAINT fk_trips_route
        FOREIGN KEY (route_id)
            REFERENCES routes (id),

    CONSTRAINT fk_trips_bus
        FOREIGN KEY (bus_id)
            REFERENCES buses (id),

    CONSTRAINT fk_trips_driver
        FOREIGN KEY (driver_id)
            REFERENCES users (user_id),

    CONSTRAINT chk_trips_status
        CHECK (
            status IN (
                       'SCHEDULED',
                       'IN_PROGRESS',
                       'COMPLETED',
                       'CANCELLED'
                )
            ),

    CONSTRAINT chk_trips_current_latitude
        CHECK (
            current_latitude IS NULL
                OR current_latitude BETWEEN -90 AND 90
            ),

    CONSTRAINT chk_trips_current_longitude
        CHECK (
            current_longitude IS NULL
                OR current_longitude BETWEEN -180 AND 180
            ),

    CONSTRAINT chk_trips_location_state
        CHECK (
            (
                current_latitude IS NULL
                    AND current_longitude IS NULL
                    AND location_updated_at IS NULL
                )
                OR
            (
                current_latitude IS NOT NULL
                    AND current_longitude IS NOT NULL
                    AND location_updated_at IS NOT NULL
                )
            ),

    CONSTRAINT chk_trips_actual_times
        CHECK (
            actual_end_time IS NULL
                OR (
                actual_start_time IS NOT NULL
                    AND actual_end_time >= actual_start_time
                )
            )
);